// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kphdqgidwipqdthehckg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwaGRxZ2lkd2lwcWR0aGVoY2tnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDkyMjYsImV4cCI6MjA3NDU4NTIyNn0.nrq7BccAJKuxU1UKk25w7wBlmCC3b8waskQOpxE-McM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});